export default[
  {
    id:'1',
    type:'BHK1',
    features:{
      wifi:true,
      balcony:true,
      gyeser:false,
      inverter:true
    },
    location:'majitar',
    price:'8,999'
  },
  {
    id:'2',
    type:'BHK1',
    features:{
      wifi:false,
      balcony:false,
      gyeser:false,
      inverter:true
    },
    location:'singtam',
    price:'5,000'
  },
  {
    id:'3',
    type:'BHK1',
    features:{
      wifi:true,
      balcony:false,
      gyeser:false,
      inverter:false
    },
    location:'majitar',
    price:'6,500'
  },
  {
    id:'4',
    type:'BHK2',
    features:{
      wifi:false,
      balcony:true,
      gyeser:true,
      inverter:true
    },
    location:'singtam',
    price:'7,999'
  },
  {
    id:'5',
    type:'BHK2',
    features:{
      wifi:true,
      balcony:true,
      gyeser:true,
      inverter:true
    },
    location:'majitar',
    price:'10,000'
  },
  {
    id:'6',
    type:'BHK1',
    features:{
      wifi:false,
      balcony:false,
      gyeser:false,
      inverter:true
    },
    location:'rangpo',
    price:'4,000'
  },
  {
    id:'7',
    type:'BHK2',
    features:{
      wifi:false,
      balcony:true,
      gyeser:true,
      inverter:false
    },
    location:'majitar',
    price:'7,000'
  }
]